name:                2Battleships
version:             0.1.0.0
github:              "githubuser/2Battleships"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/2Battleships#readme>

dependencies:
- base >= 4.7 && < 5
- HTTP
- bencode
- bytestring
- containers
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-smallcheck

library:
  source-dirs: src

executables:
  2Battleships-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2Battleships

tests:
  2Battleships-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2Battleships
